// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Vercel: uses POSTGRES_PRISMA_URL or DATABASE_URL
    // For local: uses DATABASE_URL from .env (file:./dev.db)
    // For build time: uses fallback postgresql URL (won't actually connect)
    url: process.env["POSTGRES_PRISMA_URL"] || process.env["DATABASE_URL"] || process.env["POSTGRES_URL_NON_POOLING"] || "postgresql://user:pass@localhost:5432/db",
  },
});
